version: '3'
services:
  db:
    container_name: wwbm_mysql
    image: mysql:5.7.20
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - wwbm-db-data:/var/lib/mysql
    ports:
      - ${DB_PORT}:3306
volumes:
  wwbm-db-data:
